### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by CConchelos** [wraith13/frame-phi-colors-vscode#1]
I have uninstalled this extension, and my frame colors are now stuck as the Frame Phi Colors. Maybe a 'reset frame colors' option? I am new to VS Code, so I don't know where to go from here to reset the frame specifically.

**Comment by wraith13** [comment]
Oh, I'm sorry to confuse you.

Frame Phi Colors edtis `workbench.colorCustomizations` in settings.json( both user and workspace ).
Please delete `workbench.colorCustomizations` from settings.json( both user and workspace ).

cf. https://code.visualstudio.com/docs/getstarted/settings ( You need to edit the JSON files. )

**Comment by CConchelos** [comment]
hi there. I eventually stumbled upon it. I was having trouble with the title bar, eventually I figured out it was in 2 places (user and workspace) it was very confusing. I even was trying to use Material theme to overwrite and it still wouldn't work. eventually I got it though. I still think if you remove an extension, it should rollback in some way.

**Comment by wraith13** [comment]
> I still think if you remove an extension, it should rollback in some way.

Yeah, I think too. But although extension can roll back user settings, it is not easy to roll back all workspace settings. Instead, I will add a note to the README.

**Comment by CConchelos** [comment]
Sounds good, Thanks!
